import { currentUiLanguage } from "../../../src/i18n/language";

/**
 * Fixed wording of the web shell (the parts around the shared View). The View,
 * its Toolbar and dialogs keep using the shared catalog in `src/i18n/`.
 */
const JA = {
	appName: "Semantropy",
	appSuffix: "Playground",
	tagline: "日本語の文章の意味の秩序をわざと崩し、偶然生まれた言葉に出会うための道具です。文章はこのブラウザの外へ送られません。",
	tabs: { texts: "文章", view: "本文", recompose: "再構成", collection: "収集", about: "情報" },
	tabsLabel: "画面",
	language: "表示言語",
	engine: {
		idle: "辞書: 未読み込み",
		loading: (percent: number) => `辞書を読み込んでいます… ${percent}%`,
		loadingDetail: (mb: string) => `初回だけ約${mb}MBを読み込みます`,
		ready: "辞書: 準備完了",
		failed: "辞書の読み込みに失敗しました",
		firstLoad: (mb: string) => `初回は解析用の辞書データ（約${mb}MB）を読み込みます。2回目からはブラウザのキャッシュを使います。`,
	},
	texts: {
		heading: "文章",
		document: "文章",
		groupUser: "自分の文章",
		groupPreset: "青空文庫",
		add: "新しい文章",
		duplicate: "複製して編集",
		remove: "削除",
		removeConfirm: "このテキストを削除しますか？",
		placeholder: "ここに日本語の文章を貼り付けてください。",
		presetReadOnly: "プリセットは読み取り専用です。書き換えるには「複製して編集」を使ってください。",
		chars: (count: number) => `${count.toLocaleString("ja-JP")}文字`,
		open: "Semantropyで開く",
		opening: "開いています…",
		loadingPreset: "プリセットを読み込み中…",
		presetFailed: "プリセットを読み込めませんでした。",
		vocabularyHint: "ここにある文章は、本文のツールバー「語彙を変更」で語彙ソースにも選べます。",
		newName: "文章",
		empty: "文章が空です。",
		longWarning: "長い文章です。環境によっては処理に時間がかかります。",
		persist: "このブラウザにテキストを保存する",
		persistHint: "オンにすると、自分のテキストをこのブラウザの中（IndexedDB）に保存し、次に開いたときに戻します。どこにも送信されません。",
		persistOffConfirm: "保存したテキストをこのブラウザから削除しますか？（いま開いているテキストは消えません）",
		persistFailed: "テキストを保存できませんでした。",
		persistClearFailed: "保存したテキストを削除できませんでした。ブラウザのサイトデータを削除してください。",
	},
	view: {
		empty: "「文章」で文章を貼り付けるかプリセットを選び、「Semantropyで開く」を押してください。",
		chooseText: "文章を選ぶ",
	},
	recompose: {
		heading: "再構成",
		intro: "選んだ文章の語のつながりを使って、元とは別の流れの文章を組み立てます。気になった所から続きを生成したり、分岐させたりできます。",
		sources: "再構成のソース",
		weight: "重み",
		method: "生成方式",
		methods: { joint: "継ぎ目（文節）", ngram: "形態素nグラム" },
		methodHints: {
			joint: "助詞や語尾などの「継ぎ目」が同じ別の場所へ跳びます。文法のつながりを保ったまま、中身が飛躍します。",
			ngram: "直前の数語が同じ別の場所へつながります。飛躍率を上げるほど、見る語数が減って崩れます。",
		},
		leap: "飛躍率",
		leapValue: (value: number) => `${value}`,
		sentences: "1回の文数",
		generate: "新しく生成",
		more: "続きを生成",
		branch: "選んだ位置から分岐",
		copy: "コピー",
		openAsTarget: "対象として開く",
		clear: "消去",
		showSeams: "継ぎ目を表示",
		empty: "再構成のソースを選んで「新しく生成」を押してください。",
		pickHint: "出力の語句をタップすると、その位置から分岐できます。",
		preparing: (done: number, total: number) => `再構成のソースを解析しています… ${done}/${total}`,
		ready: (sources: number, sentences: number) => `${sources}件の文章・${sentences}文`,
		noSources: "再構成のソースを1つ以上選んでください。",
		failed: "再構成できませんでした。文章を確かめてもう一度試してください。",
		tooFew: "ソースの文が足りません。文章を増やすか、長い文章を選んでください。",
		copied: "再構成した文章をコピーしました。",
		targetName: "再構成",
	},
	collection: {
		heading: "収集した断片",
		empty: "まだ何も収集していません。本文で文字列を選んで「収集」すると、ここに追加されます。",
		copy: "コピー",
		download: ".mdとして保存",
		clear: "すべて消去",
		clearConfirm: "収集した断片をすべて消去しますか？この操作は元に戻せません。",
		copied: "収集した断片をコピーしました。",
		storedHere: "収集した断片はこのブラウザの中だけに保存されます。",
	},
	about: {
		heading: "Semantropyについて",
		body: [
			"Semantropyは、日本語の文章の語を、同じ文章や選んだ文章の語と入れ替え、意味の秩序を崩した文章を作ります。上手な文章を作る道具ではありません。偶然生まれた表現の中から、気になった断片を拾い集めるための道具です。",
			"ここはObsidianプラグイン「Semantropy」を、インストールなしで試せる場所です。解析と生成はすべてこのブラウザの中で行われ、入力した文章はどこにも送信されません。アクセス解析もありません。",
		],
		steps: "使い方",
		stepList: [
			"「文章」で文章を貼り付けるか、プリセットを選びます。",
			"「Semantropyで開く」を押します。",
			"本文のツールバーで、シャッフルの強さや語彙を変えて遊びます。語をタップすると、その語だけ入れ替えられます。",
			"気に入った部分を選んで「コピー」または「収集」します。",
		],
		japaneseOnly: "Semantropy works on Japanese text only.",
		privacy: "保存されるもの",
		privacyBody: "表示設定と収集した断片は、このブラウザのローカルストレージに保存されます。貼り付けた文章は、「このブラウザにテキストを保存する」をオンにしたときだけ、このブラウザの中に保存されます。",
		obsidian: "Obsidian版",
		obsidianBody: "Obsidianのコミュニティプラグイン「Semantropy」として公開しています。",
		licenses: "ライセンスと出典",
		licensesLink: "ライセンス全文を見る",
		presetCredits: "プリセットの出典（青空文庫）",
		build: (label: string) => `ビルド: ${label}`,
	},
	errors: {
		openFailed: "開けませんでした。もう一度試してください。",
		storageUnavailable: "このブラウザでは保存が使えないため、設定と収集はこの訪問のあいだだけ保持されます。",
		clipboardFailed: "クリップボードに書き込めませんでした。",
	},
};

type ShellText = typeof JA;

const EN: ShellText = {
	appName: "Semantropy",
	appSuffix: "Playground",
	tagline: "A tool for deliberately disturbing the order of meaning in Japanese text, so you can meet words that appear by chance. Your text never leaves this browser.",
	tabs: { texts: "Texts", view: "Semantropy", recompose: "Recompose", collection: "Collection", about: "About" },
	tabsLabel: "Screens",
	language: "Language",
	engine: {
		idle: "Dictionary: not loaded",
		loading: (percent: number) => `Loading dictionary… ${percent}%`,
		loadingDetail: (mb: string) => `About ${mb} MB, on the first visit only`,
		ready: "Dictionary: ready",
		failed: "The dictionary could not be loaded",
		firstLoad: (mb: string) => `The first visit loads about ${mb} MB of dictionary data for analysis. Later visits use the browser cache.`,
	},
	texts: {
		heading: "Texts",
		document: "Document",
		groupUser: "My texts",
		groupPreset: "Aozora Bunko",
		add: "New text",
		duplicate: "Duplicate to edit",
		remove: "Delete",
		removeConfirm: "Delete this text?",
		placeholder: "Paste Japanese text here.",
		presetReadOnly: "Presets are read-only. Use “Duplicate to edit” to change one.",
		chars: (count: number) => `${count.toLocaleString("en-US")} characters`,
		open: "Open in Semantropy",
		opening: "Opening…",
		loadingPreset: "Loading preset…",
		presetFailed: "The preset could not be loaded.",
		vocabularyHint: "Any document here can be used as vocabulary through “Change vocabulary” in the Semantropy toolbar.",
		newName: "Text",
		empty: "The text is empty.",
		longWarning: "This is a long text. Processing may take a while on some devices.",
		persist: "Keep my texts in this browser",
		persistHint: "When on, your own texts are kept inside this browser (IndexedDB) and come back next time. Nothing is sent anywhere.",
		persistOffConfirm: "Delete the saved texts from this browser? (The texts open now stay.)",
		persistFailed: "Your texts could not be saved.",
		persistClearFailed: "The saved texts could not be deleted. Clear this site's data in the browser.",
	},
	view: {
		empty: "In Texts, paste Japanese text or pick a preset, then choose “Open in Semantropy”.",
		chooseText: "Choose a text",
	},
	recompose: {
		heading: "Recompose",
		intro: "Builds new passages from how words connect in the texts you choose. Continue from any point you like, or branch from it.",
		sources: "Texts to use",
		weight: "Weight",
		method: "Method",
		methods: { joint: "Joints (bunsetsu)", ngram: "Morpheme n-gram" },
		methodHints: {
			joint: "Leaps to another place that shares the same joint — a particle or ending — so the grammar holds while the content jumps.",
			ngram: "Continues from another place where the last few morphemes match. More leap means fewer morphemes matched and more breakage.",
		},
		leap: "Leap",
		leapValue: (value: number) => `${value}`,
		sentences: "Sentences per run",
		generate: "Generate anew",
		more: "Continue",
		branch: "Branch from the selected point",
		copy: "Copy",
		openAsTarget: "Open as Target",
		clear: "Clear",
		showSeams: "Show seams",
		empty: "Choose texts to use and press “Generate anew”.",
		pickHint: "Tap a phrase in the output to branch from there.",
		preparing: (done: number, total: number) => `Analyzing texts… ${done}/${total}`,
		ready: (sources: number, sentences: number) => `${sources} text(s) · ${sentences} sentences`,
		noSources: "Choose at least one text to use.",
		failed: "Could not recompose. Check the texts and try again.",
		tooFew: "Not enough sentences to work with. Add texts or choose a longer one.",
		copied: "Copied the recomposed text.",
		targetName: "Recomposed",
	},
	collection: {
		heading: "Collected fragments",
		empty: "Nothing collected yet. Select text in Semantropy and choose “Collect” to add it here.",
		copy: "Copy",
		download: "Save as .md",
		clear: "Clear all",
		clearConfirm: "Clear every collected fragment? This cannot be undone.",
		copied: "Copied the collected fragments.",
		storedHere: "Collected fragments are kept only in this browser.",
	},
	about: {
		heading: "About Semantropy",
		body: [
			"Semantropy exchanges words in Japanese text with words from the same text or from texts you choose, breaking the order of meaning. It is not a tool for writing well: it is a tool for finding and keeping the fragments that chance produces.",
			"This page lets you try the Obsidian plugin “Semantropy” without installing anything. All analysis and generation run inside this browser; your text is never sent anywhere, and there is no analytics.",
		],
		steps: "How to use",
		stepList: [
			"In Texts, paste Japanese text or pick a preset.",
			"Choose “Open in Semantropy”.",
			"Play with the level and the vocabulary in the Semantropy toolbar. Tap a word to change just that word.",
			"Select a part you like and Copy or Collect it.",
		],
		japaneseOnly: "Semantropy works on Japanese text only.",
		privacy: "What is stored",
		privacyBody: "Display settings and collected fragments are kept in this browser's local storage. Pasted text is kept in this browser only when “Keep my texts in this browser” is on.",
		obsidian: "Obsidian plugin",
		obsidianBody: "Semantropy is available as an Obsidian community plugin.",
		licenses: "Licenses and credits",
		licensesLink: "Read the full licenses",
		presetCredits: "Preset sources (Aozora Bunko)",
		build: (label: string) => `Build: ${label}`,
	},
	errors: {
		openFailed: "Could not open. Try again.",
		storageUnavailable: "Storage is unavailable in this browser, so settings and collected fragments last only for this visit.",
		clipboardFailed: "Could not write to the clipboard.",
	},
};

export function t(): ShellText {
	return currentUiLanguage() === "ja" ? JA : EN;
}
