import type {
	RawFakeProverbGloss,
	RawFakeProverbLiteral,
	RawFakeProverbProfile,
	RawFakeProverbRecipe,
} from "../../src/fakeProverb/recipeData";
import type { CompiledFakeProverbRecipeSet } from "../../src/fakeProverb/compileRecipeSet";

export declare const STANDARD_FAKE_PROVERB_RECIPES_MARKDOWN: string;
export declare const STANDARD_FAKE_PROVERB_RECIPES_GENERATED: string;
export declare const STANDARD_FAKE_PROVERB_RECIPES_LOCK: string;
export declare const FAKE_PROVERB_RECIPE_VALIDATORS: readonly string[];
export declare const GENERATE_COMMAND: string;
export declare const FAKE_PROVERB_RECIPE_SCHEMA_VERSION: number;
export declare const FAKE_PROVERB_LITERAL_MAX_CODE_POINTS: number;

export type FakeProverbSourceIssue = {
	readonly code: string;
	readonly line: number;
	readonly detail?: string;
};

export type ParsedFakeProverbRecipeDocument = {
	readonly schemaVersion: number;
	readonly dataVersion: number;
	readonly proverbs: readonly RawFakeProverbRecipe[];
	readonly glosses: readonly RawFakeProverbGloss[];
	readonly literals: readonly RawFakeProverbLiteral[];
	readonly profiles: readonly RawFakeProverbProfile[];
};

export type ParseFakeProverbRecipeDocumentResult =
	| ({ readonly ok: true } & ParsedFakeProverbRecipeDocument)
	| { readonly ok: false; readonly issues: readonly FakeProverbSourceIssue[] };

export declare function parseStandardFakeProverbRecipeMarkdown(
	markdown: string,
): ParseFakeProverbRecipeDocumentResult;

export declare function describeFakeProverbSourceIssue(issue: FakeProverbSourceIssue): string;

export declare function describeFakeProverbSourceIssues(
	issues: readonly FakeProverbSourceIssue[],
): string;

export declare function renderGeneratedFakeProverbRecipeModule(
	parsed: ParsedFakeProverbRecipeDocument,
): string;

export declare function fakeProverbRecipeDataDigest(parsed: ParsedFakeProverbRecipeDocument): string;

/**
 * `markdownPath`, `generatedPath` and `lockPath` override the files this
 * module would otherwise derive from `rootDir`. They exist so a test can
 * exercise a stale or malformed module in a temporary directory instead of
 * editing the checkout. `lockPath` is required whenever `generatedPath` is a
 * temporary file, so a version bump cannot rewrite the tracked lock. They
 * cannot make a comparison vacuous: the document is still the only source the
 * generated text and lock digest are derived from, and the lock is the
 * authority for same-version meaning changes.
 */
export type FakeProverbRecipePathOptions = {
	rootDir?: string;
	markdownPath?: string;
	generatedPath?: string;
	lockPath?: string;
};

export declare function generateStandardFakeProverbRecipes(
	options?: FakeProverbRecipePathOptions & { markdown?: string },
): Promise<{
	parsed: ParsedFakeProverbRecipeDocument;
	compiled: CompiledFakeProverbRecipeSet;
	source: string;
}>;

export declare function assertStandardFakeProverbRecipesGenerated(
	options?: FakeProverbRecipePathOptions & {
		markdown?: string;
		/**
		 * Test hook that replaces destination reads of the generated module and
		 * lock. Production never supplies this. Absence is only ENOENT; every
		 * other read failure is reported as unreadable.
		 */
		readText?: (filePath: string) => Promise<string>;
	},
): Promise<{ schemaVersion: number; dataVersion: number }>;

export declare const FAKE_PROVERB_GUARD_NAME: string;

export type FakeProverbRecipeGuardBuild = {
	/** Only `tsconfig` is read; the guard refuses to start unless it names a file. */
	initialOptions?: { tsconfig?: string };
	onStart: (
		callback: () => Promise<{
			errors?: { text: string; detail?: unknown }[];
		} | null>,
	) => void;
	onLoad: (
		options: { filter: RegExp },
		callback: (args: { path: string }) => Promise<{ contents: string; loader: "ts"; watchFiles: string[] } | null>,
	) => void;
	onResolve: (
		options: { filter: RegExp },
		callback: (args: { path: string; kind: string; resolveDir: string }) => { path: string; watchFiles: string[] } | null,
	) => void;
};

/** The esbuild plugin that repeats the check on every build and rebuild. */
export declare function standardFakeProverbRecipesPlugin(
	rootDir: string,
	options?: { readText?: (filePath: string) => Promise<string> },
): {
	name: string;
	setup: (build: FakeProverbRecipeGuardBuild) => void;
};

export declare function writeStandardFakeProverbRecipes(
	options?: FakeProverbRecipePathOptions & {
		markdown?: string;
		/** Test hook invoked immediately before each destination rename. */
		beforePublish?: (phase: "generated" | "lock") => void | Promise<void>;
		/** Test hook invoked immediately before restoring or removing generated bytes. */
		beforeRollback?: () => void | Promise<void>;
		/** Test hook invoked after rollback staging is written, before it is renamed. */
		beforeRollbackRename?: (stagingPath: string, destination: string) => void | Promise<void>;
		/** Test hook invoked immediately before removing a staging file. */
		beforeCleanup?: (filePath: string) => void | Promise<void>;
		/**
		 * Test hook that replaces destination reads of the generated module and
		 * lock. Production never supplies this. Absence is only ENOENT; every
		 * other read failure propagates before staging or publication.
		 */
		readText?: (filePath: string) => Promise<string>;
	},
): Promise<{
	outfile: string;
	schemaVersion: number;
	dataVersion: number;
	proverbs: number;
	glosses: number;
	literals: number;
	profiles: number;
}>;
