import { readFile } from "node:fs/promises";
import path from "node:path";
import {
	IPADIC_ARCHIVE,
	LINDERA_NOTICE_FILE_NAME,
	LINDERA_WASM_VERSION,
	linderaWasmLicensePath,
} from "./linderaSource.mjs";

/**
 * A Community Plugin install pulls only main.js / manifest.json / styles.css,
 * so a notice in any other file would never reach the user. The banner is
 * assembled at build time from our LICENSE and the upstream files verbatim — it is not a
 * paraphrase — and esbuild keeps it ahead of the minified code. It states
 * what this build embeds and what it changed; it does not assert that the
 * result is legally compliant.
 */
const HEADER = [
	"Semantropy",
	"",
	"THIS IS A GENERATED/BUNDLED FILE BY ESBUILD",
	"if you want to view the source, please visit the plugin source files",
	"",
	"This file contains, in addition to the Semantropy plugin code:",
	"",
	`  1. lindera-wasm ${LINDERA_WASM_VERSION}, MIT, as published on npm: its`,
	"     wasm-bindgen JavaScript glue and its WebAssembly module",
	"     (lindera_wasm_bg.wasm), embedded here as gzip. The WebAssembly",
	"     module is a compiled build of Lindera, MIT.",
	"  2. A dictionary derived from the Lindera IPADIC release archive",
	`     ${IPADIC_ARCHIVE.name}, which is itself derived from`,
	"     mecab-ipadic-2.7.0-20070801, embedded here as gzip.",
	"",
	"Semantropy's own plugin code is licensed under the MIT License.",
	"Copyright (C) 2026 Cat Left Paw / \u732b\u4e43 \u5de6\u624b.",
	"Official public repository: https://github.com/cat-left-paw/semantropy",
	"",
	"What this build does to the material above, stated as fact:",
	"",
	"  - lindera-wasm's JavaScript glue is bundled into this single file and",
	"    minified. One block of it is replaced at build time: wasm-pack's",
	"    loader, which can resolve the WebAssembly module from a URL and",
	"    retrieve it over the network, is replaced by an initializer that",
	"    accepts only the module bytes embedded in this file. Every other",
	"    export of that glue is unchanged.",
	"  - The WebAssembly module lindera_wasm_bg.wasm is embedded byte-for-byte",
	"    as published, gzipped and base64-encoded. Its contents are not",
	"    altered.",
	"  - The dictionary is a derived work of the release archive named above.",
	"    Seven of its files (metadata.json, dict.trie, dict.valsidx,",
	"    dict.vals, matrix.mtx, char_def.bin, unk.bin) are embedded",
	"    byte-for-byte. Two files (dict.words, dict.wordsidx) are rebuilt: all",
	"    392,126 system dictionary entries are kept, in the same order, each",
	"    still carrying all nine IPADIC detail slots, but detail slots that",
	"    Semantropy does not use are replaced with IPADIC's own \"*\" marker.",
	"    Part of speech and its first two subcategories are kept for every",
	"    entry; the third subcategory, base form and reading are kept for",
	"    nouns classified \u4e00\u822c, \u56fa\u6709\u540d\u8a5e, \u30b5\u5909\u63a5\u7d9a or \u5f62\u5bb9\u52d5\u8a5e\u8a9e\u5e79.",
	"    Independent verbs and i-adjectives retain the third subcategory,",
	"    conjugation type, conjugation form, base form and reading. Other",
	"    entries retain their existing compact slots. Pronunciation is dropped",
	"    for every entry. Surfaces, context IDs, word costs and the unknown-word",
	"    dictionary are unchanged.",
	"  - The lindera-wasm source files themselves are not edited on disk.",
	"",
	"Whether those steps amount to a \"modification\" under the licenses",
	"reproduced below is not assessed here.",
	"",
	"The sections below are reproduced verbatim from Semantropy's LICENSE,",
	"the installed lindera-wasm package (LICENSE), and the dictionary",
	"archive (NOTICE.txt).",
];

function frame(title) {
	return ["", "=".repeat(70), title, "=".repeat(70), ""];
}

export async function buildLinderaNotice(rootDir, dictionaryDir) {
	const ownLicense = await readFile(path.join(rootDir, "LICENSE"), "utf8");
	// The same file `packageHashes.mjs` pins, so the licence reproduced here is
	// verified before it reaches a user.
	const license = await readFile(linderaWasmLicensePath(rootDir), "utf8");
	const notice = await readFile(
		path.join(dictionaryDir, LINDERA_NOTICE_FILE_NAME),
		"utf8",
	);

	const lines = [
		...HEADER,
		...frame("Semantropy - LICENSE (verbatim)"),
		ownLicense.replace(/\s+$/, ""),
		...frame(`lindera-wasm ${LINDERA_WASM_VERSION} - LICENSE (verbatim)`),
		license.replace(/\s+$/, ""),
		...frame(`${IPADIC_ARCHIVE.name} - NOTICE.txt (verbatim)`),
		notice.replace(/\s+$/, ""),
		"",
	];

	const body = lines.join("\n");
	if (body.includes("*/")) {
		// Truncating or escaping a license/notice would change it, so
		// fail instead.
		throw new Error(
			"A bundled notice contains a block-comment terminator; the banner cannot be emitted verbatim.",
		);
	}
	return `/*\n${body}\n*/\n`;
}
