import type { RawCollisionRecipe, RawCollisionLiteral, RawCollisionConnector, RawCollisionModifierForm, RawCollisionNounSuffix } from "../../src/collision/patternData";

export declare const STANDARD_COLLISION_PATTERNS_MARKDOWN: string;
export declare const STANDARD_COLLISION_PATTERNS_GENERATED: string;
export declare const STANDARD_COLLISION_PATTERNS_LOCK: string;
export declare const GENERATE_COMMAND: string;
export declare const COLLISION_PATTERN_SCHEMA_VERSION: number;
export declare const COLLISION_LITERAL_MAX_CODE_POINTS: number;

export type CollisionSourceIssue = {
	readonly code: string;
	readonly line: number;
	readonly detail?: string;
};

export type ParsedCollisionPatternDocument = {
	readonly schemaVersion: number;
	readonly dataVersion: number;
	readonly recipes: readonly RawCollisionRecipe[];
	readonly literals: readonly RawCollisionLiteral[];
	readonly connectors: readonly RawCollisionConnector[];
	readonly modifierForms: readonly RawCollisionModifierForm[];
	readonly nounSuffixes: readonly RawCollisionNounSuffix[];
};

export type ParseCollisionPatternDocumentResult =
	| ({ readonly ok: true } & ParsedCollisionPatternDocument)
	| { readonly ok: false; readonly issues: readonly CollisionSourceIssue[] };

export declare function parseStandardCollisionPatternMarkdown(
	markdown: string,
): ParseCollisionPatternDocumentResult;

export declare function describeCollisionSourceIssue(
	issue: CollisionSourceIssue,
): string;

export declare function describeCollisionSourceIssues(
	issues: readonly CollisionSourceIssue[],
): string;

export declare function renderGeneratedCollisionPatternModule(
	parsed: ParsedCollisionPatternDocument,
): string;

export declare function collisionPatternDataDigest(
	parsed: ParsedCollisionPatternDocument,
): string;

/**
 * `markdownPath`, `generatedPath` and `lockPath` override the files this
 * module would otherwise derive from `rootDir`. They exist so a test can
 * exercise a stale or malformed module in a temporary directory instead of
 * editing the checkout. `lockPath` is required whenever `generatedPath` is a
 * temporary file, so a version bump cannot rewrite the tracked lock. They
 * cannot make a comparison vacuous: the document is still the only source the
 * generated text and lock digest are derived from, and the lock is the
 * authority for same-version meaning changes.
 */
export type CollisionPatternPathOptions = {
	rootDir?: string;
	markdownPath?: string;
	generatedPath?: string;
	lockPath?: string;
};

export declare function generateStandardCollisionPatterns(
	options?: CollisionPatternPathOptions & { markdown?: string },
): Promise<{
	parsed: ParsedCollisionPatternDocument;
	compiled: unknown;
	source: string;
}>;

export declare function assertStandardCollisionPatternsGenerated(
	options?: CollisionPatternPathOptions & {
		markdown?: string;
		/**
		 * Test hook that replaces destination reads of the generated module and
		 * lock. Production never supplies this. Absence is only ENOENT; every
		 * other read failure is reported as unreadable.
		 */
		readText?: (filePath: string) => Promise<string>;
	},
): Promise<{ schemaVersion: number; dataVersion: number }>;

export type CollisionPatternGuardBuild = {
	onStart: (
		callback: () => Promise<{
			errors?: { text: string; detail?: unknown }[];
		} | null>,
	) => void;
	onLoad: (
		options: { filter: RegExp },
		callback: (args: { path: string }) => Promise<{
			contents: string;
			loader: "ts";
			resolveDir?: string;
			watchFiles: string[];
		} | null>,
	) => void;
};

/** The esbuild plugin that repeats the check on every build and rebuild. */
export declare function standardCollisionPatternsPlugin(
	rootDir: string,
	options?: { readText?: (filePath: string) => Promise<string> },
): {
	name: string;
	setup: (build: CollisionPatternGuardBuild) => void;
};

export declare function writeStandardCollisionPatterns(
	options?: CollisionPatternPathOptions & {
		markdown?: string;
		/** Test hook invoked immediately before each destination rename. */
		beforePublish?: (phase: "generated" | "lock") => void | Promise<void>;
		/** Test hook invoked immediately before restoring or removing generated bytes. */
		beforeRollback?: () => void | Promise<void>;
		/** Test hook invoked after rollback staging is written, before it is renamed. */
		beforeRollbackRename?: (
			stagingPath: string,
			destination: string,
		) => void | Promise<void>;
		/** Test hook invoked immediately before removing a staging file. */
		beforeCleanup?: (filePath: string) => void | Promise<void>;
		/**
		 * Test hook that replaces destination reads of the generated module and
		 * lock. Production never supplies this. Absence is only ENOENT; every
		 * other read failure propagates before staging or publication.
		 */
		readText?: (filePath: string) => Promise<string>;
	},
): Promise<{
	outfile: string;
	schemaVersion: number;
	dataVersion: number;
	recipes: number;
	literals: number;
	connectors: number;
	modifierForms: number;
	nounSuffixes: number;
}>;
