/** Settings-only probes; the shared runner copies source before every mutation. */
const SETTINGS = "src/settings/automaticPosSettings.ts";
const STORE = "src/settings/AutomaticPosSettingsStore.ts";
const CONTROLLER = "src/settings/AutomaticPosSettingsController.ts";
const PURE = "tests/automaticPosSettings.test.ts";
const TRANSACTION = "tests/automaticPosSettingsController.test.ts";
export const probes = [
	[SETTINGS, PURE, "schema-3-adopts-future-options",
		"automaticPos: version >= 4 ?", "automaticPos: version >= 3 ?", "ignores future options in schema 3"],
	[SETTINGS, PURE, "migration-enables-verbs",
		"Object.freeze({ noun: true, verb: false, iAdjective: false, adverb: false });",
		"Object.freeze({ noun: true, verb: true, iAdjective: false, adverb: false });",
		"migrates schema 3 only from fields that schema owned"],
	[SETTINGS, PURE, "all-off-restores-defaults",
		"const data = settingsData(raw);\n\tconst flag =",
		"const data = settingsData(raw);\n\tif (data && AUTOMATIC_POS_KEYS.every(key => data[key] === false)) return DEFAULT_AUTOMATIC_POS;\n\tconst flag =",
		"retains all OFF on save and restore"],
	[SETTINGS, PURE, "truthy-boolean-coercion",
		'typeof data?.[key] === "boolean" ? data[key] : DEFAULT_AUTOMATIC_POS[key]',
		'data?.[key] !== undefined ? Boolean(data[key]) : DEFAULT_AUTOMATIC_POS[key]',
		"validates verb independently without truthy coercion"],
	[SETTINGS, PURE, "serializer-leaks-extra-fields",
		"return Object.freeze({ ...legacy, schemaVersion: AUTOMATIC_POS_SETTINGS_SCHEMA_VERSION,\n\t\tautomaticPos: parseAutomaticPosOptions(canonical.automaticPos), uiLanguage: canonical.uiLanguage,",
		"return Object.freeze({ ...settings, ...legacy, schemaVersion: AUTOMATIC_POS_SETTINGS_SCHEMA_VERSION,\n\t\tautomaticPos: parseAutomaticPosOptions(canonical.automaticPos), uiLanguage: canonical.uiLanguage,",
		"drops unknown and secret fields even at the serializer boundary"],
	[CONTROLLER, TRANSACTION, "draft-changes-effective",
		"this.#draft = options;\n\t\treturn true;", "this.#draft = options; this.#effective = options;\n\t\treturn true;",
		"keeps draft toggles separate from effective and every host callback"],
	[STORE, PURE, "effective-before-persistence",
		"const next = parseAutomaticPosSettings({ ...this.settings, ...patch });\n\t\t\ttry { await this.persistence.save(serializeAutomaticPosSettings(next)); }",
		"const next = parseAutomaticPosSettings({ ...this.settings, ...patch }); this.settings = next;\n\t\t\ttry { await this.persistence.save(serializeAutomaticPosSettings(next)); }",
		"commits effective settings only after persistence success"],
	[CONTROLLER, TRANSACTION, "stale-invalidation-removed",
		'this.invalidate("stale"); this.#draft = null; this.#status = "stale"; this.#error = "stale";',
		'/* defect: no stale invalidation */',
		"rejects stale completion independently of preparation and persistence"],
	[CONTROLLER, TRANSACTION, "forged-ticket-accepted-as-current",
		"complete(ticket: AutomaticPosSettingsTicket): AutomaticPosSettingsOutcome {",
		"complete(ticket: AutomaticPosSettingsTicket): AutomaticPosSettingsOutcome {\n\t\tticket = this.#current!;",
		"rejects forged cloned foreign and replayed tickets with a positive control"],
	[CONTROLLER, TRANSACTION, "dispose-invalidation-removed",
		'this.invalidate("disposed"); this.#draft = null; this.#status = "disposed"; this.#error = null; this.#host = null;',
		'/* defect: no disposal invalidation */',
		"rejects disposed completion independently of preparation and persistence"],
	[STORE, PURE, "queued-update-uses-captured-base",
		"return this.enqueue(async () => {\n\t\t\tconst savedBefore = serializeAutomaticPosSettings(this.settings);\n\t\t\tconst next = parseAutomaticPosSettings({ ...this.settings, ...patch });",
		"const base = this.settings;\n\t\treturn this.enqueue(async () => {\n\t\t\tconst savedBefore = serializeAutomaticPosSettings(this.settings);\n\t\t\tconst next = parseAutomaticPosSettings({ ...base, ...patch });",
		"composes queued fields from the last committed base"],
	["src/main.ts", "tests/automaticPosDependencies.test.ts", "production-imports-legacy-writer",
		'import {\n\tLINDERA_DICTIONARY_GZIP_BASE64,', 'import "./collect/FragmentRepository";\nimport {\n\tLINDERA_DICTIONARY_GZIP_BASE64,',
		"no longer reaches the Body 10 core from production after MAX-VIEW1: src/main.ts"],
];
