/** Development-only defect reversions. Each names a specific assertion; parse/import failures do not count. */
const AUTH = "src/transform/manualAdverbAuthority.ts";
const CONTROL = "src/transform/manualAdverbController.ts";
const GUARD = "src/transform/manualAdverbGuard.ts";
const CAPABILITY = "src/adverb/adverbCapability.ts";
const PURE = "tests/manualAdverb.test.ts";
const TRANSACTION = "tests/manualAdverbController.test.ts";
export const probes = [
	[AUTH, TRANSACTION, "logical-slot-key-restored-to-run-object",
		"const runKey = JSON.stringify([source.source.path, source.source.contentHash, source.source.projectionPolicy, located.run.runId]);",
		"const runKey = located as unknown as string;",
		"canonicalizes separately analyzed same-source slots in bind order 0 then 1"],
	[AUTH, TRANSACTION, "logical-slot-key-omits-source-identity",
		"const runKey = JSON.stringify([source.source.path, source.source.contentHash, source.source.projectionPolicy, located.run.runId]);",
		"const runKey = JSON.stringify([located.run.runId]);",
		"keeps identical run and token coordinates from different Source paths independent"],
	["src/transform/manualMorphology.ts", PURE, "owner-spread-accepted-by-minted-evidence-only",
		'return VOCABULARIES.has(value) && MINTED.get(value.evidence)?.snapshot === value.snapshot;',
		'return value != null && typeof value === "object" && !!value.snapshot && MINTED.get(value.evidence)?.snapshot === value.snapshot;',
		"accepts only minted owners and rejects snapshots clones spreads and hand-built indices"],
	[AUTH, PURE, "source-origin-check-removed",
		'if (expected.get(key)?.projectionPolicy !== source.source.projectionPolicy) refuse("invalid-evidence");', "",
		"rejects origins outside Vocabulary Sources independently of owner authentication"],
	[AUTH, PURE, "record-origin-check-removed",
		'if (!expected.has(sourceKey(origin)) || observed.origins.get(sourceKey(origin)) !== origin.count) refuse("invalid-evidence");', "",
		"checks record origins independently of the private owner registry"],
	[AUTH, PURE, "candidate-authentication-removed",
		'if (!AUTHORITIES.get(handle)!.candidates.has(value as ManualAdverbCandidate)) refuse("invalid-candidate");', "",
		"refuses foreign candidates capabilities slots and cloned evidence"],
	[AUTH, PURE, "slot-owner-not-checked", 'if (!state || state.authority !== handle) refuse("invalid-slot");',
		'if (!state) refuse("invalid-slot");', "refuses foreign candidates capabilities slots and cloned evidence"],
	[AUTH, PURE, "evaluation-owner-not-checked", 'if (!state || state.authority !== handle) refuse("invalid-evaluation");',
		'if (!state) refuse("invalid-evaluation");', "rejects foreign and cloned evaluations while their owning authority is still live"],
	[AUTH, PURE, "current-surface-not-excluded", "if (candidate.record.surface === current) continue;", "",
		"excludes current surface and counts distinct surfaces rather than records or frequency"],
	[AUTH, PURE, "frequency-counted-per-observation", "group.frequency = count(group.frequency + candidate.record.frequency);",
		"group.frequency = count(group.frequency + candidate.record.frequency * handle.observations.lookup(candidate.record.candidateId)!.profiles.length);",
		"counts a record once despite multiple observed profiles and duplicate Source handles"],
	[AUTH, PURE, "frequency-draw-made-uniform", 'handle.provenance.drawMode === "frequency" ? group.frequency : 1', "1",
		"draws with Vocabulary frequency mode without exposing the nonce"],
	[AUTH, PURE, "released-owner-remintable", 'if (REVOKED.has(vocabulary)) refuse("released");', "",
		"revokes the owner and delayed evaluations on refresh"],
	[AUTH, PURE, "target-lifetime-unchecked", "owner(state.targetVocabulary);", "",
		"rejects released Target owners even with a still-live candidate authority"],
	[AUTH, PURE, "authority-published-mutable", "const handle: ManualAdverbAuthority = frozen({", "const handle: ManualAdverbAuthority = ({",
		"keeps authenticated runs immutable without retokenizing or changing snapshots"],
	[CONTROL, TRANSACTION, "prepare-publishes-before-complete", "live(); pending.set(before.slot, { ticket, before, after }); return ticket;",
		"live(); publish(before, after); pending.set(before.slot, { ticket, before, after }); return ticket;",
		"keeps Shuffle Restore original and Use automatic result distinct"],
	[CONTROL, TRANSACTION, "cancel-keeps-ticket", "const entry = ticket(value); pending.delete(entry.before.slot); return true as const;",
		"ticket(value); return true as const;", "preserves the complete previous state on failure and cancellation"],
	[CONTROL, TRANSACTION, "failed-shuffle-does-not-supersede", "// A new valid request supersedes this slot even when it has no alternative.\n\t\t\t\tpending.delete(before.slot);", "",
		"supersedes a pending operation even when the next valid Shuffle fails"],
	[CONTROL, TRANSACTION, "ticket-identity-not-checked", "const entry = [...pending.values()].find(item => item.ticket === value);",
		"const entry = [...pending.values()][0];", "rejects superseded duplicate consumed cloned and foreign tickets"],
	[CONTROL, TRANSACTION, "other-rows-cloned-on-commit", "item === before ? after : item", "item === before ? after : { ...item }",
		"commits separate slots concurrently without losing another override"],
	[CONTROL, TRANSACTION, "manual-override-overwritten-by-baseline", 'committed: before.committed.mode === "automatic"', "committed: true",
		"changes the caller baseline without overwriting a Manual override"],
	[CONTROL, TRANSACTION, "use-automatic-confused-with-original", 'before.slot.originalSurface : before.automaticSurface', 'before.slot.originalSurface : before.slot.originalSurface',
		"keeps Shuffle Restore original and Use automatic result distinct"],
	[CONTROL, TRANSACTION, "release-no-longer-invalidates-pending-work",
		'const released = releaseManualAdverbAuthority({ authority, reason });\n\t\t\t\tif (!released.ok && released.reason !== "released") refuse(released.reason);\n\t\t\t\tauthority = null; pending.clear(); state = frozen({ rows: [] }); return true as const;',
		"return true as const;",
		"rejects late commits after view-close and releases controller state"],
	[GUARD, TRANSACTION, "revision-overflow-unchecked", 'if (!Number.isSafeInteger(value) || value < 0 || value === Number.MAX_SAFE_INTEGER) refuse("revision-overflow");', "",
		"fails closed on revision overflow without publishing a staged row"],
	[GUARD, PURE, "exception-message-leaked", 'REFUSALS.get(error as object) ?? "invalid-evidence"', 'REFUSALS.get(error as object) ?? String(error) as ManualAdverbReason',
		"never publishes a partial authority after an observation failure"],
	[GUARD, PURE, "exception-prototype-inspected", 'REFUSALS.get(error as object) ?? "invalid-evidence"', 'REFUSALS.get(error as object) ?? (error instanceof Refusal ? "invalid-input" : "invalid-evidence")',
		"never inspects the prototype or properties of an attacker-thrown exception"],
	[CAPABILITY, PURE, "head-equality-removed", "(profile) => profile.headClass === targetProfile.headClass,", "(profile) => true,",
		"does not invent unobserved heads or relax head equality"],
	[CAPABILITY, PURE, "polarity-equality-removed", "(profile) => profile.polarity === targetProfile.polarity,", "(profile) => true,",
		"requires verb polarity equality even for a to-optional candidate"],
	[CAPABILITY, PURE, "all-adverbs-to-capable", "to: optional || matching.some((profile) => profile.bridge === \"to\"),", "to: true,",
		"does not extend the bridge for a non-profiled candidate"],
	[CAPABILITY, PURE, "duplicate-to-guard-removed", 'targetProfile.bridge === "to" &&\n\t\tadverbSurfaceEndsWithTo(candidate.surface)', "false",
		"rejects duplicate to even when the exact external bridge was observed"],
];
